### PR TITLE
Redesigned website view and added some data options

### PR DESCRIPTION
**Pull request by sudheerdarla**

### CODE REVIEW

**Comment by vramana** [comment]
Can you attach a screenshot? Can you explain what is this about?

**Comment by sudheerdarla** [comment]
profilsearch
I just resigned the github profile search project. And also added the clickable links.(previously we need to copy and search them separately).

**Comment by sudheerdarla** [comment]
https://fcc-hyd.github.io/projects/github/ this is before one.

**Comment by vramana** [comment]
The goal of this project was to replicate the sidebar on the github profile. Moving away from that deviates from the goal of the project, So I don't think I will accept this. 😢  I hope this doesn't discourage you from contributing in future. Also please ping us before you work on something.

**Comment by sudheerdarla** [comment]
well what are the changes to be made then? I can replicate it also.

**Comment by vramana** [comment]
We didn't have time to add icons in live coding meetup and some of the styling hasn't done properly. We also left out the organisations part. You can work on them.

**Comment by sudheerdarla** [comment]
You mean the website https://fcc-hyd.github.io/ !?

**Comment by duttakapil** [comment]
@sudheerdarla the redesign is pretty good, but Ramana is right, we need to stick to the GitHub UI for this one. Try to follow this :  
screenshot from 2016-09-18 21-51-11

Ignore the overview and everything on the right. You can put placeholder box or just mimic the look, not the functionality.

**Comment by sudheerdarla** [comment]
Alright.. @duttakapil

**Comment by duttakapil** [comment]
And you don't have to do it alone. You can ping the Gitter chat, asking if anyone wants to pair with you to work on these changes. That would make it a much better learning experience :)

**Pull request closed without merging**
